version: '3'
services:
  web:
    build:
      context: .
      dockerfile: ./docker/ruby/Dockerfile
    command: >
      bash -c "if [ -e tmp/pids/server.pid ]; then rm tmp/pids/server.pid ;fi \
        && ./bin/bundle install \
        && ./bin/bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - 3000:3000
    volumes:
      - .:/omotenashi
    depends_on:
      - mysql
    links:
      - mysql
      - mysql:database
      - mysql:mysql
  mysql:
    build:
      context: .
      dockerfile: ./docker/mysql/Dockerfile
    ports:
      - 3306:3306
    env_file: ./docker/mysql/.mysql_env